name: cargo-get
author: n.unrein@gmail.com
branding:
  color: red
  icon: upload
description: Get cargo package metadata
inputs:
  flags:
    description: "Flags to pass to cargo get (default: package name)"
    required: false
  options:
    description: "Options to pass to cargo get"
    required: false
    default: ""
  subcommand:
    description: "Subcommand to run"
    required: false
    default: ""
outputs:
  metadata:
    description: "Cargo package metadata"
    value: ${{ steps.cargo-get.outputs.metadata }}

  # Update when cli changes
  package_name:
    value: ${{ steps.cargo-get.outputs.package_name }}
  package_edition:
    value: ${{ steps.cargo-get.outputs.package_edition }}
  package_rust_version:
    value: ${{ steps.cargo-get.outputs.package_rust_version }}
  package_version:
    value: ${{ steps.cargo-get.outputs.package_version }}
  package_build:
    value: ${{ steps.cargo-get.outputs.package_build }}
  package_workspace:
    value: ${{ steps.cargo-get.outputs.package_workspace }}
  package_authors:
    value: ${{ steps.cargo-get.outputs.package_authors }}
  package_links:
    value: ${{ steps.cargo-get.outputs.package_links }}
  package_description:
    value: ${{ steps.cargo-get.outputs.package_description }}
  package_homepage:
    value: ${{ steps.cargo-get.outputs.package_homepage }}
  package_readme:
    value: ${{ steps.cargo-get.outputs.package_readme }}
  package_keywords:
    value: ${{ steps.cargo-get.outputs.package_keywords }}
  package_categories:
    value: ${{ steps.cargo-get.outputs.package_categories }}
  package_exclude:
    value: ${{ steps.cargo-get.outputs.package_exclude }}
  package_include:
    value: ${{ steps.cargo-get.outputs.package_include }}
  package_license:
    value: ${{ steps.cargo-get.outputs.package_license }}
  package_license_file:
    value: ${{ steps.cargo-get.outputs.package_license_file }}
  package_repository:
    value: ${{ steps.cargo-get.outputs.package_repository }}
  package_default_run:
    value: ${{ steps.cargo-get.outputs.package_default_run }}
  package_publish:
    value: ${{ steps.cargo-get.outputs.package_publish }}
  package_resolver:
    value: ${{ steps.cargo-get.outputs.package_resolver }}
  package_metadata:
    value: ${{ steps.cargo-get.outputs.package_metadata }}
  workspace_members:
    value: ${{ steps.cargo-get.outputs.workspace_members }}
  workspace_default_members:
    value: ${{ steps.cargo-get.outputs.workspace_default_members }}
  workspace_package_authors:
    value: ${{ steps.cargo-get.outputs.workspace_package_authors }}
  workspace_package_categories:
    value: ${{ steps.cargo-get.outputs.workspace_package_categories }}
  workspace_package_description:
    value: ${{ steps.cargo-get.outputs.workspace_package_description }}
  workspace_package_documentation:
    value: ${{ steps.cargo-get.outputs.workspace_package_documentation }}
  workspace_package_edition:
    value: ${{ steps.cargo-get.outputs.workspace_package_edition }}
  workspace_package_exclude:
    value: ${{ steps.cargo-get.outputs.workspace_package_exclude }}
  workspace_package_homepage:
    value: ${{ steps.cargo-get.outputs.workspace_package_homepage }}
  workspace_package_include:
    value: ${{ steps.cargo-get.outputs.workspace_package_include }}
  workspace_package_keywords:
    value: ${{ steps.cargo-get.outputs.workspace_package_keywords }}
  workspace_package_license:
    value: ${{ steps.cargo-get.outputs.workspace_package_license }}
  workspace_package_license_file:
    value: ${{ steps.cargo-get.outputs.workspace_package_license_file }}
  workspace_package_publish:
    value: ${{ steps.cargo-get.outputs.workspace_package_publish }}
  workspace_package_readme:
    value: ${{ steps.cargo-get.outputs.workspace_package_readme }}
  workspace_package_repository:
    value: ${{ steps.cargo-get.outputs.workspace_package_repository }}
  workspace_package_rust_version:
    value: ${{ steps.cargo-get.outputs.workspace_package_rust_version }}
  workspace_package_version:
    value: ${{ steps.cargo-get.outputs.workspace_package_version }}
runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      name: Install cargo-get
      run: |
        download_cargo_get() {
          current_target=$(rustc -Vv | grep host | cut -d ' ' -f 2)
          download_link=$(curl -s https://api.github.com/repos/nicolaiunrein/cargo-get/releases/latest | grep $current_target\" | grep browser_download_url | cut -d: -f2,3 | tr -d '\"\ ')
          mkdir -p ~/.cargo/bin/
          curl -sSfLo ~/.cargo/bin/cargo-get "$download_link"
          chmod +x ~/.cargo/bin/cargo-get
        }

        download_cargo_get || echo "Failed for some reason!"
      shell: bash
    - if: runner.os == 'macOS'
      name: Install cargo-get
      run: |
        download_cargo_get() {
          current_target=$(rustc -Vv | grep host | cut -d ' ' -f 2)
          download_link=$(curl -s https://api.github.com/repos/nicolaiunrein/cargo-get/releases/latest | grep $current_target\" | grep browser_download_url | cut -d: -f2,3 | tr -d '\"\ ')
          mkdir -p ~/.cargo/bin/
          curl -sSfLo ~/.cargo/bin/cargo-get "$download_link"
          chmod +x ~/.cargo/bin/cargo-get
        }

        download_cargo_get || echo "Failed for some reason!"
      shell: bash
    - if: runner.os == 'Windows'
      name: Install cargo-get
      run: |
        download_cargo_get() {
          current_target=$(rustc -Vv | grep host | cut -d ' ' -f 2)
          download_link=$(curl -s https://api.github.com/repos/nicolaiunrein/cargo-get/releases/latest | grep $current_target\" | grep browser_download_url | cut -d: -f2,3 | tr -d '\"\ ')
          mkdir -p ~/.cargo/bin/
          curl -sSfLo ~/.cargo/bin/cargo-get.exe "$download_link"
          chmod +x ~/.cargo/bin/cargo-get.exe
        }

        download_cargo_get || echo "Failed for some reason!"
      shell: bash
    - name: Resort to building the binary if we can't find a prebuilt one
      run: |
        install_cargo_get() {
          if [ -n "$CARGO_GET_VERSION" ]; then
            cargo install cargo-get --version "$CARGO_GET_VERSION"
          else
            cargo install cargo-get
          fi
        }

        if [ -x "$(command -v cargo-get)" ]; then
          echo "cargo-get is already installed"
        else
          install_cargo_get
        fi
      shell: bash
    - id: cargo-get
      name: Cargo get metadata
      run: |
        if [ -n "${{ inputs.subcommand }}" ]; then
          metadata=$(cargo get ${{ inputs.flags }} ${{ inputs.options }} ${{ inputs.subcommand }})
          echo "metadata=$metadata" >> $GITHUB_OUTPUT
        else
          echo "$(cargo get all --output-format github-action)" >> $GITHUB_OUTPUT
        fi
      shell: bash
