name: cargo-get
author: n.unrein@gmail.com
branding:
  color: red
  icon: upload
description: Get cargo package metadata
inputs:
  flags:
    description: "Flags to pass to cargo get (default: package name)"
    required: false
  options:
    description: "Options to pass to cargo get"
    required: false
    default: ""
  subcommand:
    description: "Subcommand to run"
    required: false
    default: ""
outputs:
  metadata:
    description: "Cargo package metadata"
    value: ${{ steps.cargo-get.outputs.metadata }}
runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      name: Install cargo-get
      run: |
        current_target=$(rustc -Vv | grep host | cut -d ' ' -f 2)
        download_link=$(curl -s https://api.github.com/repos/nicolaiunrein/cargo-get/releases/latest | grep x86_64-unknown-linux-musl\" | grep browser_download_url | cut -d: -f2,3 | tr -d '\"\ ')
        mkdir -p ~/.cargo/bin/
        curl -sSfLo ~/.cargo/bin/cargo-get "$download_link"
        chmod +x ~/.cargo/bin/cargo-get
      shell: bash
    - if: runner.os == 'macOS'
      name: Install cargo-get
      run: |
        current_target=$(rustc -Vv | grep host | cut -d ' ' -f 2)
        download_link=$(curl -s https://api.github.com/repos/nicolaiunrein/cargo-get/releases/latest | grep x86_64-apple-darwin\" | grep browser_download_url | cut -d: -f2,3 | tr -d '\"\ ')
        mkdir -p ~/.cargo/bin/
        curl -sSfLo ~/.cargo/bin/cargo-get "$download_link"
        chmod +x ~/.cargo/bin/cargo-get
      shell: bash
    - if: failed()
      name: Resort to building the binary instead
      run: |
        if [[ ! -z "$CARGO_GET_VERSION"]]; then
          cargo install cargo-get --version "$CARGO_GET_VERSION"
        else
          cargo install cargo-get
        fi
      shell: bash
    - id: cargo-get
      name: Cargo get metadata
      run: |
        metadata=$(cargo get ${{ inputs.flags }} ${{ inputs.options }} ${{ inputs.subcommand }})
        echo "metadata=$metadata" >> $GITHUB_OUTPUT
      shell: bash
